void bigWhiteSpace();
void whiteSpace();
void quadWhiteSpace();
void hexaWhiteSpace();
void lineBreaks();
void printErrorMessage(char cError);
void showStartScreen();
void printLogin();
void printRegistration();
void printInputUsername();
void printInputPassword();
void printInputPasswordRepeat();
void printSuccessMessage(char cUsername);
void showDifficulty();
void showLoggedInStartScreen();
void printFieldHorizontal();
void printField(sudoku_field sudoku_fields[8][8]);
void showHighscore();
void printSelector(int iPosition, int iSelector);
void showIntro();