void bigWhiteSpace();
void whiteSpace();
void quadWhiteSpace();
void hexaWhiteSpace();
void lineBreaks();
void printErrorMessage(char cError);
void showStartScreen(int iSelector);
void printLogin();
void printRegistration();
void printInputUsername();
void printInputPassword();
void printInputPasswordRepeat();
void printSuccessMessage(char cUsername);
void showDifficulty(int iSelector);
void showLoggedInStartScreen(int iSelector);
void printFieldHorizontal();
void printField(sudoku_field sudoku_fields[8][8]);
void showHighscore();
void printSelector(int iPosition, int iSelector);
void showIntro();